# Generated by Django 4.1 on 2022-09-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_topic_id_alter_webpage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
